DROP TABLE PHOTOS;
CREATE TABLE PHOTOS(
    photoid INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
    filename VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL,
    total INTEGER NOT NULL,
    imagecontent BLOB NOT NULL,
    submissiondate DATE NOT NULL,
    price DECIMAL(6,2) NOT NULL,
    winner INTEGER NOT NULL,
    FOREIGN KEY (email) REFERENCES ACCOUNT
);